version: "3.8"

services:
  gateway:
    image: kong/kong-gateway:3.4
    container_name: gateway
    volumes:
      - ./kong.yaml:/usr/src/app/twitter-api/kong.yaml
    env_file:
      - .env
    ports:
      - "8000:8000" # Kong's proxy
      - "8001:8001" # Kong Admin API
      - "8444:8444" # Kong Admin API
    networks:
      - api-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/data
      - zookeeper:/datalog
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - api-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9101:9101"
    volumes:
      - kafka:/conduktor/kafka
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - api-network

  account:
    build: ./account
    container_name: account
    ports:
      - "3001:3000"
    depends_on:
#      - user-db
      - gateway
      - kafka
    env_file:
      - account/.env
    volumes:
      - ./account:/twitter-api/account
      - node-modules-account:/twitter-api/account/node_modules
    networks:
      - api-network

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "3002:3000"
    env_file:
      - notification/.env
    volumes:
      - ./notification:/twitter-api/notification
      - node-modules-notification:/twitter-api/notification/node_modules
    networks:
      - api-network
    depends_on:
      - kafka

  followings:
    build: ./followings
    container_name: followings
    ports:
      - "3003:3000"
    depends_on:
      - gateway
      - kafka
      - followings-db
    env_file:
      - followings/.env
    volumes:
      - ./followings:/twitter-api/followings
      - node-modules-followings:/twitter-api/followings/node_modules
    networks:
      - api-network

  tweets:
    build: ./tweets
    container_name: tweets
    ports:
      - "3004:3000"
    depends_on:
      - gateway
      - kafka
#      - tweets-db
    env_file:
      - tweets/.env
    volumes:
      - ./tweets:/twitter-api/tweets
      - node-modules-tweets:/twitter-api/tweets/node_modules
    networks:
      - api-network


  user-db:
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    container_name: user-db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongodb-user:/data/db
    networks:
      - api-network

  followings-db:
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    container_name: followings-db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - mongodb-followings:/data/db
    networks:
      - api-network

  tweets-db:
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    container_name: tweets-db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27020:27017"
    volumes:
      - mongodb-tweets:/data/db
    networks:
      - api-network

volumes:
  mongodb-user:
  mongodb-followings:
  mongodb-tweets:
  kafka:
  zookeeper:
  node-modules-account:
  node-modules-notification:
  node-modules-followings:
  node-modules-tweets:


networks:
  api-network:
    name: api-network